### ISSUE TITLE
Ignore save button

### ISSUE THREAD

**Issue by warmwhisky** [simon-reynolds/jquery.dirty#47]
Do you have an example of how to stop the message appearing when you click a save/submit button?

**Comment by simon-reynolds** [comment]
Hi @warmwhisky,

You should be able to use `$("#myForm").dirty("setAsClean");` in your save/submit function to set the form state as the "clean" version when saving the form.

Does that take care of it?

**Comment by warmwhisky** [comment]
Hi @simon-reynolds 

Sorry for the late replay. I'd been on leave. That does take care of it for me thank you.

I'd actually set $("#myForm") not to the form but the surrounding table ID. When I changed it to the form ID all was good.
